# Copyright 2020 New Relic Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Go Telemetry SDK CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - go-version: 1.13
          - go-version: 1.14
          - go-version: 1.15
          - go-version: 1.16
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Fmt
      run: go fmt ./...

    - name: Vet
      run: go vet ./...
      env:
        CGO_ENABLED: 0

    - name: Lint
      run: |
        go get -u golang.org/x/lint/golint
        golint -set_exit_status ./...

    - name: Test
      run: go test -benchtime=1ms -bench=. ./...
      env:
        CGO_ENABLED: 0

